server:
  #指定服务端口 
  port: 8761
eureka:  
  instance:  
    hostname: localhost
  client:
    #是否将eureka自身作为应用注册到eureka注册中心
    registerWithEureka: false 
    #为true时，可以启动，但报异常：Cannot execute request on any known server 
    fetchRegistry: false  
    serviceUrl:  
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ 