# 多环境通用部分[各个环境可以覆盖通用字段]
spring:  
  application: 
    # 通用名字,其他环境可以覆盖：为你的应用起个名字，该名字将注册到eureka注册中心
    name: service-a
    
# 控制台日志打印
logging: 
  level:  
    com.netflix: DEBUG
    
# 服务配置
server:  
  # 服务提供监听端口[eureka客户端],注意改端口不能与本机服务器端口冲突
  port: 8762
  
# eureka配置
eureka:
  client:
    #从eureka服务器获取注册表信息的频率（以秒为单位）-用于客户端
    registry-fetch-interval-seconds: 10
    # 是否将eureka自身作为应用注册到eureka注册中心,默认为true
    registerWithEureka: true
    service-url:
      # 这里可以填写所有的eureka服务器地址并以','分离，当前面不能注册时候,自动选择后面的进行注册，排除单点故障问题
      defaultZone: http://localhost:8761/eureka/
  instance: 
    #配置与服务器心跳间隔-用于客户端
    lease-renewal-interval-in-seconds: 30
    #配置服务超时时间(此值将设置为至少高于leaseRenewalIntervalInSeconds中指定的值)-用于客户端
    #当服务关闭超过,这个时间时,eureka服务器会清除掉这个服务,配置此项要关闭服务器的自我保护模式-用于客户端
    lease-expiration-duration-in-seconds: 60
    #客户端自定义数据元数据-给其他eureka客户端调用--用户客户端
    metadata-map: 
      #自定义元数据serverid
      serverid: client_8762